version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  # mysql:
  #   image: mysql
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: recipebook
  #     MYSQL_DATABASE: recipebook
  #     MYSQL_USER: recipebook

#    docker run -d \
#    --name=zookeeper \
#    -e ZOOKEEPER_CLIENT_PORT=32181 \
#    confluentinc/cp-zookeeper:3.2.1

#  echo "*** Starting Zookeeper ***"
#  docker run -d \
#  --network kafka-net \
#  --name zookeeper \
#  --restart unless-stopped \
#  --env ZOOKEEPER_CLIENT_PORT=2181 \
#  --env ZOOKEEPER_TICK_TIME=2000 \
#  confluentinc/cp-zookeeper:latest
#
#  echo "*** Starting Kafka ***"
#  docker run -d \
#  --network kafka-net \
#  --name kafka-0 \
#  --publish 9092:9092 \
#  --restart unless-stopped \
#  --env KAFKA_BROKER_ID=0 \
#  --env KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 \
#  --env KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:29092,PLAINTEXT_HOST://localhost:9092 \
#  --env KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT \
#  --env KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT \
#  --env KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
#  confluentinc/cp-kafka:latest